export enum UrlServices {
    sendUserInfo = '/login',
    getUser = '/user/',
    updateHistorialCDC = '/update/historial/cdc/',
    newMember = '/clients/',
    groupAssignment = '/groups/',
    group = '/group/',
    clientAssignment = '/addClient/',
    allGroups = '/groups/?creditOfficerUsername=',
    fullDetails = '?fullDetails=true',
    loans = '/loans',
    consularCDC = '/consultacdcembajadores/',
    generarNip = '/consultacdc/nip/nuevo',
    validarNIP = '/consultacdc/nip/validar',
    consultasAnteriores = '/consultacdc/anteriores',
    resendNip = '/consultacdc/nip/reenvio',
    saveSolicitudes = '/save/solicitudes/individuales/',
    loan = '/loan/',
    loanDetail = '/loandetails',
    searchConsultation = '/consultacdc/search',
    querySepomex = '/consultacdc/zipcode/info'
}
